---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # Required so the sidecar instrument tool can access the service process
      containers:
        # Container for the instrumented service
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80

